+define+TARGET_ASAP7
+define+ASAP7_SRAM
rtl/cpu/core/cpu_pkg.sv
rtl/cpu/cache/cache_pkg.sv
rtl/cpu/cache/axi_pkg.sv
rtl/lib/asap7/srambank_64x4x20_6t122.v
rtl/lib/asap7/srambank_64x4x48_6t122.v
rtl/lib/asap7/srambank_64x4x64_6t122.v
rtl/lib/asap7/srambank_256x4x64_6t122.v
rtl/lib/sram_256x20_1rw.sv
rtl/lib/sram_256x48_1rw.sv
rtl/lib/sram_256x64_1rw.sv
rtl/lib/sram_1024x64_1rw.sv
rtl/cpu/core/riscv_core_7stg.sv
rtl/cpu/core/hazard_ctrl_7stg.sv
rtl/cpu/core/mispredict_reg.sv
rtl/cpu/core/hdu_7stg.sv
rtl/cpu/core/fcu1.sv
rtl/cpu/core/if1_if2_pipeline.sv
rtl/cpu/core/dbp_7stg_asap7.sv
rtl/cpu/core/dbp_7stg.sv
rtl/cpu/core/fcu2.sv
rtl/cpu/core/if2_id_pipeline.sv
rtl/cpu/core/cu.sv
rtl/cpu/core/rf.sv
rtl/cpu/core/immgen.sv
rtl/cpu/core/id_ex_pipeline.sv
rtl/cpu/core/fu_7stg.sv
rtl/cpu/core/fwd_mux_7stg.sv
rtl/cpu/core/alu_operand_mux.sv
rtl/cpu/core/alu.sv
rtl/cpu/core/bru.sv
rtl/cpu/core/ex_mem1_pipeline.sv
rtl/cpu/core/lsu1.sv
rtl/cpu/core/mem1_mem2_pipeline.sv
rtl/cpu/core/lsu2.sv
rtl/cpu/core/mem2_wb_pipeline.sv
rtl/cpu/core/wb.sv
rtl/cpu/cache/icache_7stg_asap7.sv
rtl/cpu/cache/icache_7stg.sv
rtl/cpu/cache/dcache_7stg_asap7.sv
rtl/cpu/cache/dcache_7stg.sv
rtl/cpu/cache/write_buffer.sv
rtl/cpu/cache/bus_arbiter.sv
rtl/cpu/cache/cache_subsystem_7stg.sv
rtl/cpu/riscv_soc_7stg.sv
