# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/constrs/kv260.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fpga_top_wrapper_0_0/design_1_fpga_top_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fpga_top_wrapper_0_0 || ORIG_REF_NAME==design_1_fpga_top_wrapper_0_0} -quiet] -quiet

# XDC: /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/work/fpga_demo/fpga_demo.gen/sources_1/bd/design_1/design_1_ooc.xdc
