# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/quocviet/fpga_a7/fpga_a7.runs/synth_1/fpga_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-599380-quocviet-workstation/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 3
set_param general.usePosixSpawnForFork 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/quocviet/fpga_a7/fpga_a7.cache/wt [current_project]
set_property parent.project_path /home/quocviet/fpga_a7/fpga_a7.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/quocviet/.Xilinx/Vivado/2025.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/quocviet/fpga_a7/fpga_a7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/cpu_pkg.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/alu.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/alu_operand_mux.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/cache_pkg.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/fpga/axi_bram.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/fpga/axi_decoder.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/axi_pkg.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/bru.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/bus_arbiter.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/cache_subsystem.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/cu.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/dbp.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/dcache.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/ex_mem_pipeline.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/fcu.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/fu.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/fwd_mux.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/hazard_ctrl.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/hdu.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/icache.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/id_ex_pipeline.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/if_id_pipeline.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/immgen.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/lsu.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/mem_wb_pipeline.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/mispredict_reg.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/rf.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/riscv_core.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/riscv_soc.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/fpga/uart_axi.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/fpga/uart_tx.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/core/wb.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/cpu/cache/write_buffer.sv
  /home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/rtl/fpga/fpga_top.sv
}
read_ip -quiet /home/quocviet/fpga_a7/fpga_a7.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/quocviet/fpga_a7/fpga_a7.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/quocviet/fpga_a7/fpga_a7.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/quocviet/fpga_a7/fpga_a7.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/quocviet/fpga_a7/fpga_a7.srcs/constrs_1/new/fpga_a7.xdc
set_property used_in_implementation false [get_files /home/quocviet/fpga_a7/fpga_a7.srcs/constrs_1/new/fpga_a7.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/quocviet/fpga_a7/fpga_a7.srcs/utils_1/imports/synth_1/fpga_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
