set_property SRC_FILE_INFO {cfile:/home/quocviet/Project/Advanced-RISC-V-32-bit-SoC/constrs/kv260.xdc rfile:../../constrs/kv260.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G21 IOSTANDARD LVCMOS18 } [get_ports clk_300mhz]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H12 IOSTANDARD LVCMOS33 } [get_ports rst_n_i]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G12 IOSTANDARD LVCMOS33 } [get_ports uart_tx_o]
